[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "16-bit-target.json"

[target.'cfg(target_os = "none")']
# rustflags = ["-Clink-args=--script=./16-bit.ld"]
# rustflags = ["-Clink-args=-shared"]
# rustflags = ["-Clink-arg=-fuse-ld=lld"]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld", "-Clink-args=-Wl,-T,foo.ld"]
runner = "./run.sh"
